### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <:> at index 2:

### ISSUE THREAD

**Issue by diskostu** [gwt-test-utils/gwt-test-utils#87] opened 2018-12-05 11:15 UTC
I followed the instructions in the wiki and now have a very very simple JUnit Test which doesn't even has GWT code in it, it just runs `System.out.println("Hello");`.

But, I get this exception:
```java
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/DEV/paas/intellij_2018.3/lib/idea_rt.jar

	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.gwt.dev.cfg.ResourceLoaders$ContextClassLoaderAdapter.getClassPath(ResourceLoaders.java:62)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.addAllClassPathEntries(ResourceOracleImpl.java:315)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.getAllClassPathEntries(ResourceOracleImpl.java:353)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.<init>(ResourceOracleImpl.java:387)
	at com.google.gwt.dev.cfg.ModuleDef.normalize(ModuleDef.java:678)
	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:200)
	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:170)
	at com.google.gwt.dev.cfg.ModuleDefLoader.createSyntheticModule(ModuleDefLoader.java:100)
	at com.googlecode.gwt.test.internal.GwtFactory.createModuleDef(GwtFactory.java:165)
	at com.googlecode.gwt.test.internal.GwtFactory.<init>(GwtFactory.java:118)
	at com.googlecode.gwt.test.internal.GwtFactory.initializeIfNeeded(GwtFactory.java:54)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.<init>(AbstractGwtRunner.java:27)
	at com.googlecode.gwt.test.GwtRunner.<init>(GwtRunner.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I googled, but with no luck. I have no idea what I can do now. :/

**Comment by ChronosMasterOfAllTime** [comment] 2019-04-24 17:51
I am experiencing this same issue.

I would think the issue is with GWT 2.8.2 itself and not gwt-test-utils

Based on this line `at com.google.gwt.dev.resource.impl.ResourceOracleImpl.getAllClassPathEntries(ResourceOracleImpl.java:353)`

See the following URL:
https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/resource/impl/ResourceOracleImpl.java#L348

**Comment by nbartels** [comment] 2019-09-05 14:43
I don't think so. Because in the GwtFactory::addToClassPath an URL array is added to the class path and at this point the error occurs. 

The URL-array is reduced to a String, the path separator is used correctly, but the `getPath` on the URL produces a bad path, like:

```
/D:/works/project1/war/WEB-INF/classes/;/D:/works/project1/war/WEB-INF/lib/commons-httpclient-3.1.jar;
```

The `getPath` don't creates valid paths, so this need to be changed. I try something and hopefully I can provide a fix for this.

**Closed** 2020-02-15 02:07 UTC

**Comment by gorshkov-leonid** [comment] 2023-09-21 12:18
@nbartels @Gael could you please release this changes?
